### ISSUE TITLE
buffer-reverse instead buffertools.reverse

### ISSUE THREAD

**Issue by fanatid** [mappum/blockchain-spv#11]
`blockchain-spv` uses only `reverse` from `buffertools`, but `buffertools` need C++ for building and `buffertools-buffer` for browser, why not use [crypto-browserify/buffer-reverse](https://github.com/crypto-browserify/buffer-reverse)?

**Comment by mappum** [comment]
Sure, `buffer-reverse` is probably a good choice for simplicity.
