### ISSUE TITLE
When I make a header stream, is it inclusive of from and to blocks?

### ISSUE THREAD

**Issue by paulkernfeld** [mappum/blockchain-spv#16]
For example, if I do, 

```
chain.createReadStream({ from: 'abcdef' })
```

does this include block `abcdef`?

**Comment by mappum** [comment]
That's funny that you ask that, I was just trying to decide which way it should be.

My current thinking is that being non-inclusive for `from` should be the default. This makes sense for things like wallet syncs where you want all the blocks _after_ the last block you have synced to (so you can use the latest block you know about so far as `from`).

There is now a `inclusive` option (which maybe should be renamed to something better, like `skipFirst`).

But I still haven't thought about inclusiveness for `to`. @paulkernfeld do you have any opinions based on your use case?

**Comment by paulkernfeld** [comment]
Ha, I have actually never used `to`, so I couldn't tell you. Maybe it should be the opposite of `from`? I.e. if `from` is exclusive then `to` should be inclusive?

**Comment by mappum** [comment]
Now I think the best choice is to be exclusive of `from`, since it matches your use case and mine in `bitcoin-wallet`. Also, in the case that you would need it to be inclusive, rather than adding an option it's pretty easy to just use `from: header.prevHash` to start at the previous block.

**Comment by mappum** [comment]
Now exclusive as of c79cade14ac65b9371dac48116d620b78c2851b0

**Comment by paulkernfeld** [comment]
Awesome, thanks!
