### ISSUE TITLE
Ability to stream from a block height?

### ISSUE THREAD

**Issue by paulkernfeld** [mappum/blockchain-spv#17]
This is pretty low-priority, I think. Right now, I need to get a live stream starting at block height _n+1_, where _n_ is what I've already stored locally. So, the process is:
1. Look up the hash of the block at height _n+1_
2. Start streaming blocks at the block after the block in question.

This usually works fine, except when the tip of the chain is at height _n_, I would need to wait until a new block appears, because there is no block of height _n+1_. It might be cool if there were a way to stream from a particular block height. This also relates to #16, because if `from` were exclusive then maybe that solves my problem...

**Comment by mappum** [comment]
I think this will be solved by being _exclusive_ of `from` by default.

**Comment by paulkernfeld** [comment]
Yup definitely.
